apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: coverage-reports-data
  labels:
    app: coverage-reports
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
